This code is used for preparing wind data thus suitable with wave data in terms of time and also calculating the magnitude of wind.

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import xarray as xr
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib
import matplotlib.pyplot as plt

# Baron

In [ ]:
ds = xr.open_dataset('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/baron_raw.nc')  # sesuaikan disini
ds

<xarray.Dataset>
Dimensions:    (longitude: 3, latitude: 2, time: 2208)
Coordinates:
  * longitude  (longitude) float32 110.5 110.8 111.0
  * latitude   (latitude) float32 -8.0 -8.25
  * time       (time) datetime64[ns] 2014-07-01 ... 2014-09-30T23:00:00
Data variables:
    u10        (time, latitude, longitude) float32 ...
    v10        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-01-15 10:36:56 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [ ]:
df = ds.to_dataframe()
df

                                             u10       v10
longitude latitude time
110.5     -8.00    2014-07-01 00:00:00 -2.203103  1.398670
                   2014-07-01 01:00:00 -3.392029  2.414171
                   2014-07-01 02:00:00 -3.629533  2.920198
                   2014-07-01 03:00:00 -3.880769  3.196610
                   2014-07-01 04:00:00 -3.864228  3.195948
...                                          ...       ...
111.0     -8.25    2014-09-30 19:00:00 -4.203944  1.221024
                   2014-09-30 20:00:00 -4.235309  1.133128
                   2014-09-30 21:00:00 -4.361395  1.118413
                   2014-09-30 22:00:00 -4.867613  1.340338
                   2014-09-30 23:00:00 -4.891801  1.369372

[13248 rows x 2 columns]

In [ ]:
df2=df.reset_index()
df2

       longitude  latitude                time       u10       v10
0          110.5     -8.00 2014-07-01 00:00:00 -2.203103  1.398670
1          110.5     -8.00 2014-07-01 01:00:00 -3.392029  2.414171
2          110.5     -8.00 2014-07-01 02:00:00 -3.629533  2.920198
3          110.5     -8.00 2014-07-01 03:00:00 -3.880769  3.196610
4          110.5     -8.00 2014-07-01 04:00:00 -3.864228  3.195948
...          ...       ...                 ...       ...       ...
13243      111.0     -8.25 2014-09-30 19:00:00 -4.203944  1.221024
13244      111.0     -8.25 2014-09-30 20:00:00 -4.235309  1.133128
13245      111.0     -8.25 2014-09-30 21:00:00 -4.361395  1.118413
13246      111.0     -8.25 2014-09-30 22:00:00 -4.867613  1.340338
13247      111.0     -8.25 2014-09-30 23:00:00 -4.891801  1.369372

[13248 rows x 5 columns]

In [ ]:
#filtering based on lat lon
new_df = df2.loc[(df2['longitude']==110.5) & (df2['latitude']==-8.00) ]
new_df

      longitude  latitude                time       u10       v10
0         110.5      -8.0 2014-07-01 00:00:00 -2.203103  1.398670
1         110.5      -8.0 2014-07-01 01:00:00 -3.392029  2.414171
2         110.5      -8.0 2014-07-01 02:00:00 -3.629533  2.920198
3         110.5      -8.0 2014-07-01 03:00:00 -3.880769  3.196610
4         110.5      -8.0 2014-07-01 04:00:00 -3.864228  3.195948
...         ...       ...                 ...       ...       ...
2203      110.5      -8.0 2014-09-30 19:00:00 -1.031187  1.153677
2204      110.5      -8.0 2014-09-30 20:00:00 -1.139640  0.943683
2205      110.5      -8.0 2014-09-30 21:00:00 -1.598575  0.954422
2206      110.5      -8.0 2014-09-30 22:00:00 -1.829525  0.883230
2207      110.5      -8.0 2014-09-30 23:00:00 -2.133974  1.094948

[2208 rows x 5 columns]

In [ ]:
new_df.dtypes

longitude           float64
latitude            float64
time         datetime64[ns]
u10                 float32
v10                 float32
dtype: object

In [ ]:

#filtering based on date
new_df = new_df.loc[(df2['time'] >= '2014-07-14 15:00:00')
                     & (df2['time'] < '2014-09-05 04:00:00')]

In [ ]:
new_df

      longitude  latitude                time       u10       v10
327       110.5      -8.0 2014-07-14 15:00:00 -2.869426  2.204044
328       110.5      -8.0 2014-07-14 16:00:00 -2.650959  2.007175
329       110.5      -8.0 2014-07-14 17:00:00 -2.585732  1.915701
330       110.5      -8.0 2014-07-14 18:00:00 -2.476030  1.651485
331       110.5      -8.0 2014-07-14 19:00:00 -2.200606  1.374144
...         ...       ...                 ...       ...       ...
1583      110.5      -8.0 2014-09-04 23:00:00  0.120912 -0.844844
1584      110.5      -8.0 2014-09-05 00:00:00  0.003564 -0.119544
1585      110.5      -8.0 2014-09-05 01:00:00 -0.153732  0.664089
1586      110.5      -8.0 2014-09-05 02:00:00 -0.452251  0.995651
1587      110.5      -8.0 2014-09-05 03:00:00  0.041483  1.483118

[1261 rows x 5 columns]

In [ ]:
#calculate magnitude
import math
new_df['mag'] = new_df.apply(lambda x: math.sqrt(x['u10']**2 +x['v10']**2),axis=1)
new_df

      longitude  latitude                time       u10       v10       mag
327       110.5      -8.0 2014-07-14 15:00:00 -2.869426  2.204044  3.618206
328       110.5      -8.0 2014-07-14 16:00:00 -2.650959  2.007175  3.325107
329       110.5      -8.0 2014-07-14 17:00:00 -2.585732  1.915701  3.218061
330       110.5      -8.0 2014-07-14 18:00:00 -2.476030  1.651485  2.976261
331       110.5      -8.0 2014-07-14 19:00:00 -2.200606  1.374144  2.594406
...         ...       ...                 ...       ...       ...       ...
1583      110.5      -8.0 2014-09-04 23:00:00  0.120912 -0.844844  0.853453
1584      110.5      -8.0 2014-09-05 00:00:00  0.003564 -0.119544  0.119597
1585      110.5      -8.0 2014-09-05 01:00:00 -0.153732  0.664089  0.681651
1586      110.5      -8.0 2014-09-05 02:00:00 -0.452251  0.995651  1.093551
1587      110.5      -8.0 2014-09-05 03:00:00  0.041483  1.483118  1.483698

[1261 rows x 6 columns]

In [ ]:
new_df = new_df[['time','mag']]
new_df

                    time       mag
327  2014-07-14 15:00:00  3.618206
328  2014-07-14 16:00:00  3.325107
329  2014-07-14 17:00:00  3.218061
330  2014-07-14 18:00:00  2.976261
331  2014-07-14 19:00:00  2.594406
...                  ...       ...
1583 2014-09-04 23:00:00  0.853453
1584 2014-09-05 00:00:00  0.119597
1585 2014-09-05 01:00:00  0.681651
1586 2014-09-05 02:00:00  1.093551
1587 2014-09-05 03:00:00  1.483698

[1261 rows x 2 columns]

In [ ]:
new_df.to_csv('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/baron_angin.csv')

# Belawan

In [ ]:
ds = xr.open_dataset('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/belawan_raw.nc')  # sesuaikan disini
ds

<xarray.Dataset>
Dimensions:    (longitude: 2, latitude: 2, time: 16032)
Coordinates:
  * longitude  (longitude) float32 99.0 99.25
  * latitude   (latitude) float32 4.0 3.75
  * time       (time) datetime64[ns] 1998-01-01 ... 1999-12-31T23:00:00
Data variables:
    u10        (time, latitude, longitude) float32 ...
    v10        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-01-15 10:58:20 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [ ]:
df = ds.to_dataframe()
df

                                             u10       v10
longitude latitude time
99.00     4.00     1998-01-01 00:00:00  2.218918 -0.720413
                   1998-01-01 01:00:00  1.459346 -0.626202
                   1998-01-01 02:00:00  1.348851 -0.628617
                   1998-01-01 03:00:00  1.349285 -0.667268
                   1998-01-01 04:00:00  1.183868 -0.686835
...                                          ...       ...
99.25     3.75     1999-12-31 19:00:00  1.860298 -0.737806
                   1999-12-31 20:00:00  1.699440 -0.482227
                   1999-12-31 21:00:00  2.299239  0.132803
                   1999-12-31 22:00:00  2.533688 -0.387050
                   1999-12-31 23:00:00  3.056423  0.049463

[64128 rows x 2 columns]

In [ ]:
df2=df.reset_index()
df2

       longitude  latitude                time       u10       v10
0          99.00      4.00 1998-01-01 00:00:00  2.218918 -0.720413
1          99.00      4.00 1998-01-01 01:00:00  1.459346 -0.626202
2          99.00      4.00 1998-01-01 02:00:00  1.348851 -0.628617
3          99.00      4.00 1998-01-01 03:00:00  1.349285 -0.667268
4          99.00      4.00 1998-01-01 04:00:00  1.183868 -0.686835
...          ...       ...                 ...       ...       ...
64123      99.25      3.75 1999-12-31 19:00:00  1.860298 -0.737806
64124      99.25      3.75 1999-12-31 20:00:00  1.699440 -0.482227
64125      99.25      3.75 1999-12-31 21:00:00  2.299239  0.132803
64126      99.25      3.75 1999-12-31 22:00:00  2.533688 -0.387050
64127      99.25      3.75 1999-12-31 23:00:00  3.056423  0.049463

[64128 rows x 5 columns]

In [ ]:
#filtering based on lat lon
new_df = df2.loc[(df2['longitude']==99.0) & (df2['latitude']==4.00) ]
new_df

       longitude  latitude                time       u10       v10
0           99.0       4.0 1998-01-01 00:00:00  2.218918 -0.720413
1           99.0       4.0 1998-01-01 01:00:00  1.459346 -0.626202
2           99.0       4.0 1998-01-01 02:00:00  1.348851 -0.628617
3           99.0       4.0 1998-01-01 03:00:00  1.349285 -0.667268
4           99.0       4.0 1998-01-01 04:00:00  1.183868 -0.686835
...          ...       ...                 ...       ...       ...
16027       99.0       4.0 1999-12-31 19:00:00  1.909141 -0.006339
16028       99.0       4.0 1999-12-31 20:00:00  1.934757  0.633814
16029       99.0       4.0 1999-12-31 21:00:00  2.214359  1.130960
16030       99.0       4.0 1999-12-31 22:00:00  2.525873  0.154061
16031       99.0       4.0 1999-12-31 23:00:00  2.874725  0.268323

[16032 rows x 5 columns]

In [ ]:
new_df.dtypes

longitude           float64
latitude            float64
time         datetime64[ns]
u10                 float32
v10                 float32
dtype: object

In [ ]:
#filtering based on date
new_df = new_df.loc[(df2['time'] >= '1999-07-10 22:00:00')
                     & (df2['time'] < '1999-07-29 08:00:00')]

In [ ]:
new_df

       longitude  latitude                time       u10       v10
12598       99.0       4.0 1999-07-10 22:00:00 -2.229321  1.569164
12599       99.0       4.0 1999-07-10 23:00:00 -1.382482  2.212216
12600       99.0       4.0 1999-07-11 00:00:00 -1.204692  2.770479
12601       99.0       4.0 1999-07-11 01:00:00 -1.248108  3.231631
12602       99.0       4.0 1999-07-11 02:00:00 -1.214895  3.748827
...          ...       ...                 ...       ...       ...
13035       99.0       4.0 1999-07-29 03:00:00  2.217616 -0.344051
13036       99.0       4.0 1999-07-29 04:00:00  1.519478 -0.504452
13037       99.0       4.0 1999-07-29 05:00:00  1.272438 -0.762204
13038       99.0       4.0 1999-07-29 06:00:00  0.686966 -1.117792
13039       99.0       4.0 1999-07-29 07:00:00  0.610336 -1.646583

[442 rows x 5 columns]

In [ ]:
#calculate magnitude
import math
new_df['mag'] = new_df.apply(lambda x: math.sqrt(x['u10']**2 +x['v10']**2),axis=1)
new_df

       longitude  latitude                time       u10       v10       mag
12598       99.0       4.0 1999-07-10 22:00:00 -2.229321  1.569164  2.726197
12599       99.0       4.0 1999-07-10 23:00:00 -1.382482  2.212216  2.608670
12600       99.0       4.0 1999-07-11 00:00:00 -1.204692  2.770479  3.021065
12601       99.0       4.0 1999-07-11 01:00:00 -1.248108  3.231631  3.464277
12602       99.0       4.0 1999-07-11 02:00:00 -1.214895  3.748827  3.940771
...          ...       ...                 ...       ...       ...       ...
13035       99.0       4.0 1999-07-29 03:00:00  2.217616 -0.344051  2.244146
13036       99.0       4.0 1999-07-29 04:00:00  1.519478 -0.504452  1.601026
13037       99.0       4.0 1999-07-29 05:00:00  1.272438 -0.762204  1.483258
13038       99.0       4.0 1999-07-29 06:00:00  0.686966 -1.117792  1.312014
13039       99.0       4.0 1999-07-29 07:00:00  0.610336 -1.646583  1.756059

[442 rows x 6 columns]

In [ ]:
new_df = new_df[['time','mag']]
new_df

                     time       mag
12598 1999-07-10 22:00:00  2.726197
12599 1999-07-10 23:00:00  2.608670
12600 1999-07-11 00:00:00  3.021065
12601 1999-07-11 01:00:00  3.464277
12602 1999-07-11 02:00:00  3.940771
...                   ...       ...
13035 1999-07-29 03:00:00  2.244146
13036 1999-07-29 04:00:00  1.601026
13037 1999-07-29 05:00:00  1.483258
13038 1999-07-29 06:00:00  1.312014
13039 1999-07-29 07:00:00  1.756059

[442 rows x 2 columns]

In [ ]:
new_df.to_csv('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/belawan_angin.csv')

# Masalembo

In [ ]:
ds = xr.open_dataset('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/masalembo_raw.nc')  # sesuaikan disini
ds

<xarray.Dataset>
Dimensions:    (longitude: 2, latitude: 2, time: 1464)
Coordinates:
  * longitude  (longitude) float32 114.5 114.8
  * latitude   (latitude) float32 5.5 5.25
  * time       (time) datetime64[ns] 1998-10-01 ... 1998-11-30T23:00:00
Data variables:
    u10        (time, latitude, longitude) float32 ...
    v10        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-01-15 10:39:17 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [ ]:
df = ds.to_dataframe()
df

                                             u10       v10
longitude latitude time
114.50    5.50     1998-10-01 00:00:00  5.908606  3.931803
                   1998-10-01 01:00:00  4.294737  4.503641
                   1998-10-01 02:00:00  2.727035  5.530126
                   1998-10-01 03:00:00  1.766248  6.067136
                   1998-10-01 04:00:00  1.580493  6.245511
...                                          ...       ...
114.75    5.25     1998-11-30 19:00:00 -1.198864 -1.223447
                   1998-11-30 20:00:00 -0.728487  0.000945
                   1998-11-30 21:00:00 -0.490686  0.709507
                   1998-11-30 22:00:00 -1.056662  0.003769
                   1998-11-30 23:00:00  0.096848  0.713978

[5856 rows x 2 columns]

In [ ]:
df2=df.reset_index()
df2

      longitude  latitude                time       u10       v10
0        114.50      5.50 1998-10-01 00:00:00  5.908606  3.931803
1        114.50      5.50 1998-10-01 01:00:00  4.294737  4.503641
2        114.50      5.50 1998-10-01 02:00:00  2.727035  5.530126
3        114.50      5.50 1998-10-01 03:00:00  1.766248  6.067136
4        114.50      5.50 1998-10-01 04:00:00  1.580493  6.245511
...         ...       ...                 ...       ...       ...
5851     114.75      5.25 1998-11-30 19:00:00 -1.198864 -1.223447
5852     114.75      5.25 1998-11-30 20:00:00 -0.728487  0.000945
5853     114.75      5.25 1998-11-30 21:00:00 -0.490686  0.709507
5854     114.75      5.25 1998-11-30 22:00:00 -1.056662  0.003769
5855     114.75      5.25 1998-11-30 23:00:00  0.096848  0.713978

[5856 rows x 5 columns]

In [ ]:
#filtering based on lat lon
new_df = df2.loc[(df2['longitude']==114.5) & (df2['latitude']==5.5) ]
new_df

      longitude  latitude                time       u10       v10
0         114.5       5.5 1998-10-01 00:00:00  5.908606  3.931803
1         114.5       5.5 1998-10-01 01:00:00  4.294737  4.503641
2         114.5       5.5 1998-10-01 02:00:00  2.727035  5.530126
3         114.5       5.5 1998-10-01 03:00:00  1.766248  6.067136
4         114.5       5.5 1998-10-01 04:00:00  1.580493  6.245511
...         ...       ...                 ...       ...       ...
1459      114.5       5.5 1998-11-30 19:00:00 -1.082576 -0.719618
1460      114.5       5.5 1998-11-30 20:00:00 -0.484371  0.477477
1461      114.5       5.5 1998-11-30 21:00:00 -0.035554  0.460534
1462      114.5       5.5 1998-11-30 22:00:00 -0.523351 -0.445465
1463      114.5       5.5 1998-11-30 23:00:00  0.227726 -0.244969

[1464 rows x 5 columns]

In [ ]:
new_df.dtypes

longitude           float64
latitude            float64
time         datetime64[ns]
u10                 float32
v10                 float32
dtype: object

In [ ]:
#filtering based on date
new_df = new_df.loc[(df2['time'] >= '1998-10-30 11:00:00')
                     & (df2['time'] <= '1998-11-12 20:00:00')]

In [ ]:
new_df

      longitude  latitude                time       u10       v10
707       114.5       5.5 1998-10-30 11:00:00  1.152146 -3.068861
708       114.5       5.5 1998-10-30 12:00:00 -0.136162 -2.621744
709       114.5       5.5 1998-10-30 13:00:00 -1.762661 -1.362524
710       114.5       5.5 1998-10-30 14:00:00 -2.266791 -1.120375
711       114.5       5.5 1998-10-30 15:00:00 -2.465177 -1.105079
...         ...       ...                 ...       ...       ...
1024      114.5       5.5 1998-11-12 16:00:00  4.797996  6.618030
1025      114.5       5.5 1998-11-12 17:00:00  4.881618  6.828645
1026      114.5       5.5 1998-11-12 18:00:00  5.683653  6.569788
1027      114.5       5.5 1998-11-12 19:00:00  6.818871  5.721209
1028      114.5       5.5 1998-11-12 20:00:00  6.953233  4.945344

[322 rows x 5 columns]

In [ ]:
#calculate magnitude
import math
new_df['mag'] = new_df.apply(lambda x: math.sqrt(x['u10']**2 +x['v10']**2),axis=1)
new_df

      longitude  latitude                time       u10       v10       mag
707       114.5       5.5 1998-10-30 11:00:00  1.152146 -3.068861  3.278009
708       114.5       5.5 1998-10-30 12:00:00 -0.136162 -2.621744  2.625278
709       114.5       5.5 1998-10-30 13:00:00 -1.762661 -1.362524  2.227879
710       114.5       5.5 1998-10-30 14:00:00 -2.266791 -1.120375  2.528553
711       114.5       5.5 1998-10-30 15:00:00 -2.465177 -1.105079  2.701536
...         ...       ...                 ...       ...       ...       ...
1024      114.5       5.5 1998-11-12 16:00:00  4.797996  6.618030  8.174294
1025      114.5       5.5 1998-11-12 17:00:00  4.881618  6.828645  8.394081
1026      114.5       5.5 1998-11-12 18:00:00  5.683653  6.569788  8.687118
1027      114.5       5.5 1998-11-12 19:00:00  6.818871  5.721209  8.901080
1028      114.5       5.5 1998-11-12 20:00:00  6.953233  4.945344  8.532519

[322 rows x 6 columns]

In [ ]:
new_df = new_df[['time','mag']]
new_df

                    time       mag
707  1998-10-30 11:00:00  3.278009
708  1998-10-30 12:00:00  2.625278
709  1998-10-30 13:00:00  2.227879
710  1998-10-30 14:00:00  2.528553
711  1998-10-30 15:00:00  2.701536
...                  ...       ...
1024 1998-11-12 16:00:00  8.174294
1025 1998-11-12 17:00:00  8.394081
1026 1998-11-12 18:00:00  8.687118
1027 1998-11-12 19:00:00  8.901080
1028 1998-11-12 20:00:00  8.532519

[322 rows x 2 columns]

In [ ]:
new_df.to_csv('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/masalembo_angin.csv')

# Karawang

In [ ]:
ds = xr.open_dataset('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/karawang_raw.nc')  # sesuaikan disini
ds

<xarray.Dataset>
Dimensions:    (longitude: 2, latitude: 2, time: 6552)
Coordinates:
  * longitude  (longitude) float32 107.8 108.0
  * latitude   (latitude) float32 -5.75 -6.0
  * time       (time) datetime64[ns] 1999-01-01 ... 1999-09-30T23:00:00
Data variables:
    u10        (time, latitude, longitude) float32 ...
    v10        (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-01-15 10:43:52 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [ ]:
df = ds.to_dataframe()
df

                                             u10       v10
longitude latitude time
107.75    -5.75    1999-01-01 00:00:00  9.012724  0.668441
                   1999-01-01 01:00:00  8.870913  0.144284
                   1999-01-01 02:00:00  8.852253  0.175434
                   1999-01-01 03:00:00  8.627719  0.553600
                   1999-01-01 04:00:00  8.660684  0.213230
...                                          ...       ...
108.00    -6.00    1999-09-30 19:00:00 -4.309740  2.393340
                   1999-09-30 20:00:00 -4.036691  3.249559
                   1999-09-30 21:00:00 -3.873111  3.834979
                   1999-09-30 22:00:00 -3.763954  4.370142
                   1999-09-30 23:00:00 -3.539731  4.668977

[26208 rows x 2 columns]

In [ ]:
df2=df.reset_index()
df2

       longitude  latitude                time       u10       v10
0         107.75     -5.75 1999-01-01 00:00:00  9.012724  0.668441
1         107.75     -5.75 1999-01-01 01:00:00  8.870913  0.144284
2         107.75     -5.75 1999-01-01 02:00:00  8.852253  0.175434
3         107.75     -5.75 1999-01-01 03:00:00  8.627719  0.553600
4         107.75     -5.75 1999-01-01 04:00:00  8.660684  0.213230
...          ...       ...                 ...       ...       ...
26203     108.00     -6.00 1999-09-30 19:00:00 -4.309740  2.393340
26204     108.00     -6.00 1999-09-30 20:00:00 -4.036691  3.249559
26205     108.00     -6.00 1999-09-30 21:00:00 -3.873111  3.834979
26206     108.00     -6.00 1999-09-30 22:00:00 -3.763954  4.370142
26207     108.00     -6.00 1999-09-30 23:00:00 -3.539731  4.668977

[26208 rows x 5 columns]

In [ ]:
#filtering based on lat lon
new_df = df2.loc[(df2['longitude']==107.75) & (df2['latitude']==-5.75) ]
new_df

      longitude  latitude                time       u10       v10
0        107.75     -5.75 1999-01-01 00:00:00  9.012724  0.668441
1        107.75     -5.75 1999-01-01 01:00:00  8.870913  0.144284
2        107.75     -5.75 1999-01-01 02:00:00  8.852253  0.175434
3        107.75     -5.75 1999-01-01 03:00:00  8.627719  0.553600
4        107.75     -5.75 1999-01-01 04:00:00  8.660684  0.213230
...         ...       ...                 ...       ...       ...
6547     107.75     -5.75 1999-09-30 19:00:00 -5.130751  1.084817
6548     107.75     -5.75 1999-09-30 20:00:00 -5.011331  2.101150
6549     107.75     -5.75 1999-09-30 21:00:00 -4.851483  2.995165
6550     107.75     -5.75 1999-09-30 22:00:00 -4.598027  3.839755
6551     107.75     -5.75 1999-09-30 23:00:00 -4.116926  3.957088

[6552 rows x 5 columns]

In [ ]:
new_df.dtypes

longitude           float64
latitude            float64
time         datetime64[ns]
u10                 float32
v10                 float32
dtype: object

In [ ]:
#filtering based on date
new_df = new_df.loc[(df2['time'] >= '1999-01-12 07:00:00')
                     & (df2['time'] <= '1999-06-13 06:00:00')]

In [ ]:
new_df

      longitude  latitude                time       u10       v10
271      107.75     -5.75 1999-01-12 07:00:00  2.562187 -2.310364
272      107.75     -5.75 1999-01-12 08:00:00  2.346672 -2.169565
273      107.75     -5.75 1999-01-12 09:00:00  2.268302 -2.639728
274      107.75     -5.75 1999-01-12 10:00:00  2.333610 -2.915720
275      107.75     -5.75 1999-01-12 11:00:00  2.636825 -2.269454
...         ...       ...                 ...       ...       ...
3914     107.75     -5.75 1999-06-13 02:00:00 -4.087382  2.269777
3915     107.75     -5.75 1999-06-13 03:00:00 -4.163886  1.950174
3916     107.75     -5.75 1999-06-13 04:00:00 -4.186899  1.594852
3917     107.75     -5.75 1999-06-13 05:00:00 -4.153001  1.217933
3918     107.75     -5.75 1999-06-13 06:00:00 -4.612954  0.610501

[3648 rows x 5 columns]

In [ ]:
#calculate magnitude
import math
new_df['mag'] = new_df.apply(lambda x: math.sqrt(x['u10']**2 +x['v10']**2),axis=1)
new_df

      longitude  latitude                time       u10       v10       mag
271      107.75     -5.75 1999-01-12 07:00:00  2.562187 -2.310364  3.450012
272      107.75     -5.75 1999-01-12 08:00:00  2.346672 -2.169565  3.195916
273      107.75     -5.75 1999-01-12 09:00:00  2.268302 -2.639728  3.480425
274      107.75     -5.75 1999-01-12 10:00:00  2.333610 -2.915720  3.734589
275      107.75     -5.75 1999-01-12 11:00:00  2.636825 -2.269454  3.478974
...         ...       ...                 ...       ...       ...       ...
3914     107.75     -5.75 1999-06-13 02:00:00 -4.087382  2.269777  4.675316
3915     107.75     -5.75 1999-06-13 03:00:00 -4.163886  1.950174  4.597948
3916     107.75     -5.75 1999-06-13 04:00:00 -4.186899  1.594852  4.480365
3917     107.75     -5.75 1999-06-13 05:00:00 -4.153001  1.217933  4.327907
3918     107.75     -5.75 1999-06-13 06:00:00 -4.612954  0.610501  4.653177

[3648 rows x 6 columns]

In [ ]:
new_df = new_df[['time','mag']]
new_df

                    time       mag
271  1999-01-12 07:00:00  3.450012
272  1999-01-12 08:00:00  3.195916
273  1999-01-12 09:00:00  3.480425
274  1999-01-12 10:00:00  3.734589
275  1999-01-12 11:00:00  3.478974
...                  ...       ...
3914 1999-06-13 02:00:00  4.675316
3915 1999-06-13 03:00:00  4.597948
3916 1999-06-13 04:00:00  4.480365
3917 1999-06-13 05:00:00  4.327907
3918 1999-06-13 06:00:00  4.653177

[3648 rows x 2 columns]

In [ ]:
new_df.to_csv('/content/drive/MyDrive/TA (1)/Processing Data/Data/raw data/karawang_angin.csv')